version: "3.3"

services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs

  nodejs:
    image: node:latest
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    command: ["node", "index"]
